#############################################################################
# Makefile for building: GO-ClipImg.app/Contents/MacOS/GO-ClipImg
# Generated by qmake (3.1) (Qt 5.9.2)
# Project:  GO-ClipImg.pro
# Template: app
# Command: /Applications/Qt/5.9.2/clang_64/bin/qmake -o Makefile GO-ClipImg.pro -spec macx-clang CONFIG+=x86_64
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.9.2/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Qt/5.9.2/clang_64/mkspecs/macx-clang -F/Applications/Qt/5.9.2/clang_64/lib
QMAKE         = /Applications/Qt/5.9.2/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Applications/Qt/5.9.2/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Applications/Qt/5.9.2/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = GO-ClipImg1.0.0
DISTDIR = /Users/haodaquan/Qt/QtGuiStudy/GO-ClipImg/.tmp/GO-ClipImg1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Applications/Qt/5.9.2/clang_64/lib
LIBS          = $(SUBLIBS) -F/Applications/Qt/5.9.2/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /Applications/Qt/5.9.2/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/sanitize.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/toolchain.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/toolchain.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/qmake_use.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/file_copies.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/lex.prf \
		GO-ClipImg.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = GO-ClipImg
DESTDIR       = 
TARGET        = GO-ClipImg.app/Contents/MacOS/GO-ClipImg

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d GO-ClipImg.app/Contents/MacOS/ || mkdir -p GO-ClipImg.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GO-ClipImg.pro /Applications/Qt/5.9.2/clang_64/mkspecs/macx-clang/qmake.conf /Applications/Qt/5.9.2/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/sanitize.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/toolchain.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/toolchain.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/qmake_use.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/file_copies.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.9.2/clang_64/mkspecs/features/lex.prf \
		GO-ClipImg.pro \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/Qt/5.9.2/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile GO-ClipImg.pro -spec macx-clang CONFIG+=x86_64
/Applications/Qt/5.9.2/clang_64/mkspecs/features/spec_pre.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/qdevice.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/device_config.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/common/unix.conf:
/Applications/Qt/5.9.2/clang_64/mkspecs/common/mac.conf:
/Applications/Qt/5.9.2/clang_64/mkspecs/common/macx.conf:
/Applications/Qt/5.9.2/clang_64/mkspecs/common/sanitize.conf:
/Applications/Qt/5.9.2/clang_64/mkspecs/common/gcc-base.conf:
/Applications/Qt/5.9.2/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/Qt/5.9.2/clang_64/mkspecs/common/clang.conf:
/Applications/Qt/5.9.2/clang_64/mkspecs/common/clang-mac.conf:
/Applications/Qt/5.9.2/clang_64/mkspecs/qconfig.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_location.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/qt_functions.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/qt_config.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/spec_post.prf:
../.qmake.stash:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/toolchain.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/toolchain.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/default_pre.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/resolve_config.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/default_post.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/warn_on.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/qt.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/resources.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/moc.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/uic.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/unix/thread.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/qmake_use.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/file_copies.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/rez.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/exceptions.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/yacc.prf:
/Applications/Qt/5.9.2/clang_64/mkspecs/features/lex.prf:
GO-ClipImg.pro:
/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/Qt/5.9.2/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile GO-ClipImg.pro -spec macx-clang CONFIG+=x86_64

qmake_all: FORCE

GO-ClipImg.app/Contents/PkgInfo: 
	@test -d GO-ClipImg.app/Contents || mkdir -p GO-ClipImg.app/Contents
	@$(DEL_FILE) GO-ClipImg.app/Contents/PkgInfo
	@echo "APPL????" > GO-ClipImg.app/Contents/PkgInfo
GO-ClipImg.app/Contents/Resources/empty.lproj: 
	@test -d GO-ClipImg.app/Contents/Resources || mkdir -p GO-ClipImg.app/Contents/Resources
	@touch GO-ClipImg.app/Contents/Resources/empty.lproj
	
GO-ClipImg.app/Contents/Info.plist: 
	@test -d GO-ClipImg.app/Contents || mkdir -p GO-ClipImg.app/Contents
	@$(DEL_FILE) GO-ClipImg.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.GO-ClipImg,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,GO-ClipImg,g" -e "s,@LIBRARY@,GO-ClipImg,g" -e "s,@TYPEINFO@,????,g" /Applications/Qt/5.9.2/clang_64/mkspecs/macx-clang/Info.plist.app >GO-ClipImg.app/Contents/Info.plist

all: Makefile \
		GO-ClipImg.app/Contents/PkgInfo \
		GO-ClipImg.app/Contents/Resources/empty.lproj \
		GO-ClipImg.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Applications/Qt/5.9.2/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r GO-ClipImg.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Applications/Qt/5.9.2/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h /Applications/Qt/5.9.2/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QCache \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qcache.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QFile \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qfile.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QFileInfoList \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QTableView \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QSize \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qsize.h \
		mainwindow.h \
		moc_predefs.h \
		/Applications/Qt/5.9.2/clang_64/bin/moc
	/Applications/Qt/5.9.2/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Applications/Qt/5.9.2/clang_64/mkspecs/macx-clang -I/Users/haodaquan/Qt/QtGuiStudy/GO-ClipImg -I/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.9.2/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Applications/Qt/5.9.2/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/Applications/Qt/5.9.2/clang_64/bin/uic
	/Applications/Qt/5.9.2/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QCache \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qcache.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QFile \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qfile.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QFileInfoList \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QTableView \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QSize \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qsize.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QCache \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qcache.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QFile \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qfile.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QFileInfoList \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QTableView \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QSize \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qsize.h \
		ui_mainwindow.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QProcess \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

